language: php
php:
  - 5.3
  # - 5.4

env:
  - SYMFONY_VERSION=v2.0.11
  - SYMFONY_VERSION=origin/2.0

before_script: php Tests/tests/vendors.php
script: phpunit

notifications:
    webhooks: http://sonata-project.org/bundles/admin/2-0/travis